/*
 * Controle de versionamento funcional
 * Ao alterar um pilar, incremente sua versão e atualize o respectivo arquivo
 * VERSIONAMENTO-*.md e o RESUMO-DE-VERSOES.md na mesma alteração.
 */
const VERSOES_ATUAIS = Object.freeze({
  design: 'V1',
  perguntas: 'V2',
  funcionalidades: 'V2'
});

const modules = {
  journey:{title:'Busca, descoberta e decisão',copy:'A busca é uma ação deliberada. A descoberta pode acontecer antes, durante ou depois dela — em redes, vídeos, recomendações e assistentes. A decisão é o resultado de muitos encontros, não de uma única página.',example:'DESCOBRE no LinkedIn\n→ PESQUISA no Google\n→ ASSISTE no YouTube\n→ COMPARA alternativas\n→ RETORNA e decide',tip:'Pergunta-guia: em quais momentos sua marca pode ser útil antes da compra?'},
  crawl:{title:'Rastreamento e indexação',copy:'O robots.txt orienta os rastreadores sobre áreas que não devem ser acessadas. O sitemap.xml destaca URLs importantes que você quer que sejam descobertas. Eles têm papéis diferentes e complementares.',example:'User-agent: *\nDisallow: /checkout/\nDisallow: /busca/\n\nSitemap: https://veloce.com/sitemap.xml',tip:'Priorize no sitemap páginas canônicas, úteis e com potencial de aparecer nos resultados.'},
  technical:{title:'SEO técnico com propósito',copy:'Cada recurso técnico protege uma parte do valor já construído: canonical para duplicidades, 301 para mudanças permanentes, 404 para ausências e 5xx para falhas do servidor.',example:'URL com parâmetros\n/tenis-velocity?utm_source=instagram\n\n<link rel="canonical" href="/tenis-velocity">',tip:'A pergunta de negócio é: qual é a versão oficial que deve concentrar tráfego e relevância?'},
  architecture:{title:'Arquitetura e links internos',copy:'A estrutura do site é uma forma de comunicar prioridade. Uma página pilar conecta temas amplos; os clusters aprofundam assuntos e apontam caminhos para a próxima ação.',example:'HOME\n└── Tênis de corrida (pilar)\n    ├── Guia para iniciantes\n    ├── Tênis masculinos\n    └── Velocity Pro (produto)',tip:'Evite páginas órfãs: se ninguém chega até elas por links internos, elas perdem contexto e força.'},
  intent:{title:'As cinco intenções de busca',copy:'A mesma palavra pode significar coisas muito diferentes. Entender o momento do usuário permite criar uma resposta adequada — em vez de apenas repetir uma palavra-chave.',example:'“o que é amortecimento” → Informacional\n“Veloce tênis” → Navegacional\n“melhor tênis para iniciantes” → Comercial\n“comprar Velocity Pro” → Transacional\n“loja de tênis perto” → Local',tip:'A intenção muda a página, o conteúdo, a profundidade da informação e a chamada para ação.'},
  content:{title:'Página otimizada e conteúdo original',copy:'Uma página clara usa URL descritiva, title e meta aderentes, hierarquia de títulos, imagens contextualizadas e dados estruturados quando fizer sentido. Mas seu maior diferencial é entregar algo que não seja commodity.',example:'URL: /tenis-corrida/iniciantes\nTITLE: Melhor tênis para iniciantes | Veloce\nH1: Como escolher seu primeiro tênis de corrida\nALT: Corredora usando tênis com amortecimento',tip:'Originalidade pode vir de dados próprios, experiência real, metodologia clara ou uma visão que gere ação.'}
};
const dialog=document.querySelector('#module-dialog');
document.querySelectorAll('.open-module').forEach(button=>button.addEventListener('click',()=>{const m=modules[button.dataset.module];document.querySelector('#module-content').innerHTML=`<p class="dialog-eyebrow">CAMADA DA TRILHA</p><h2 class="dialog-title">${m.title}</h2><p class="dialog-copy">${m.copy}</p><div class="dialog-example">${m.example}</div><p class="dialog-tip"><strong>Para testar:</strong> ${m.tip}</p>`;dialog.showModal();}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});
document.querySelector('#jump-to-challenge').addEventListener('click',()=>document.querySelector('#desafio').scrollIntoView());
const nameInput=document.querySelector('#student-name'),nameLabel=document.querySelector('#student-label');
nameInput.addEventListener('input',()=>nameLabel.textContent=`Participante: ${nameInput.value.trim()||'visitante'}`);

const questions=[
  {type:'builder',builder:'robots',title:'Mapa de acesso dos rastreadores',copy:'Defina quem pode ser rastreado em cada área. O robots.txt será construído em tempo real.',metric:'crawl',impact:42,ready:s=>Object.keys(s).length===10,validate:s=>s.busca==='Disallow'&&s.filtros==='Disallow'&&s.produtos==='Allow'&&s.categorias==='Allow'&&s.guias==='Allow',feedback:'Buscas internas e filtros consomem rastreamento sem trazer valor; produtos, categorias e guias precisam seguir acessíveis.'},
  {type:'builder',builder:'sitemap',title:'Seleção para o sitemap.xml',copy:'Monte uma lista enxuta das três páginas que o buscador deve encontrar primeiro.',metric:'index',impact:35,ready:s=>Object.keys(s).filter(k=>s[k]).length===3,validate:s=>s.categoria&&s.produto&&s.guia&&Object.keys(s).filter(k=>s[k]).length===3,feedback:'O sitemap é uma curadoria: use as versões canônicas de páginas úteis, não filtros, buscas ou URLs desativadas.'},
  {type:'builder',builder:'architecture',title:'Arquitetura da nova família de corrida',copy:'Organize categoria, guia e produto em uma rota que o site consiga expandir sem perder contexto.',metric:'architecture',impact:42,ready:s=>s.category&&s.guide&&s.product,validate:s=>s.category==='corrida'&&s.guide==='guia'&&s.product==='produto',feedback:'A hierarquia deve começar pelo tema, aprofundar com o guia e conectar naturalmente ao produto.'},
  {type:'builder',builder:'brief',title:'Quadro de intenção de busca',copy:'Componha uma resposta para quem está comparando tênis de corrida para iniciantes.',metric:'relevance',impact:25,ready:s=>s.format&&s.elements?.length>=2&&s.next,validate:s=>s.format==='Guia comparativo'&&s.elements?.includes('Critérios de escolha')&&s.elements?.includes('Modelos e faixas de preço')&&s.next==='Explorar categorias',feedback:'A intenção comercial pede critérios e alternativas antes de uma chamada para compra.'},
  {type:'builder',builder:'canonical',title:'Central de URLs do Velocity Pro',copy:'Escolha qual endereço deverá receber a autoridade das demais variações do produto.',metric:'index',impact:30,ready:s=>Boolean(s.url),validate:s=>s.url==='https://veloce.com.br/tenis-velocity-pro/',feedback:'A URL canônica é a versão estável e limpa do produto, sem referências de campanha ou filtros.'},
  {type:'builder',builder:'onpage',title:'Mesa de edição da categoria',copy:'Monte a página escolhendo uma peça para cada camada da experiência de busca.',metric:'relevance',impact:25,ready:s=>s.url&&s.title&&s.h1&&s.content&&s.image,validate:s=>s.url==='boa'&&s.title==='bom'&&s.h1==='bom'&&s.content==='bom'&&s.image==='bom',feedback:'A página precisa unir contexto, hierarquia e utilidade — não apenas repetir termos ou empurrar a compra.'},
  {type:'builder',builder:'scenario',title:'O endereço antigo ainda recebe visitas',copy:'A página /tenis-velocity-pro foi substituída pelo novo produto. Monte a rota que preserva a experiência e a relevância já conquistada.',metric:'architecture',impact:20,fields:[{key:'status',label:'Resposta da URL antiga',options:[['301','Redirecionamento permanente (301)'],['200','Página vazia com status 200'],['500','Erro do servidor (5xx)']]},{key:'destination',label:'Destino da visita',options:[['new','Página do novo produto equivalente'],['home','Home genérica'],['empty','Manter a URL antiga vazia']]}],ready:s=>s.status&&s.destination,validate:s=>s.status==='301'&&s.destination==='new',feedback:'Para uma mudança permanente, o redirecionamento 301 leva visitantes e mecanismos de busca da URL antiga ao destino equivalente.'},
  {type:'builder',builder:'scenario',title:'Um produto saiu de linha. E agora?',copy:'O modelo Velocity 2019 não será vendido novamente e não existe substituto equivalente. Configure uma saída útil para quem chegar a essa URL.',metric:'crawl',impact:18,fields:[{key:'status',label:'Status da página',options:[['404','404 — página não encontrada'],['200','200 — página vazia'],['301','301 — redirecionamento genérico']]},{key:'experience',label:'Experiência entregue',options:[['helpful','Navegação e alternativas relevantes'],['blank','Tela sem conteúdo'],['home','Enviar diretamente para a home']]}],ready:s=>s.status&&s.experience,validate:s=>s.status==='404'&&s.experience==='helpful',feedback:'Quando não há uma substituição relevante, uma 404 clara e útil é preferível a um redirecionamento genérico ou a uma página vazia.'},
  {type:'builder',builder:'scenario',title:'O servidor está fora do ar',copy:'Durante uma instabilidade, a Veloce precisa responder corretamente a pessoas e buscadores. Defina o sinal técnico e a prioridade da equipe.',metric:'crawl',impact:20,fields:[{key:'status',label:'Sinal enviado pelo servidor',options:[['5xx','Status 5xx — indisponibilidade temporária'],['200','Status 200 — simular normalidade'],['robots','Bloquear tudo no robots.txt']]},{key:'action',label:'Próxima ação',options:[['fix','Corrigir e restaurar o serviço rapidamente'],['wait','Manter a página sem informar falha'],['hide','Ocultar a falha dos buscadores']]}],ready:s=>s.status&&s.action,validate:s=>s.status==='5xx'&&s.action==='fix',feedback:'Códigos 5xx avisam que o servidor falhou temporariamente. A prioridade é restaurar o serviço, não esconder o problema.'},
  {type:'builder',builder:'scenario',title:'O guia está isolado no site',copy:'O conteúdo “Como escolher seu primeiro tênis” é útil, mas quase ninguém o encontra. Construa uma conexão que acompanhe a jornada de descoberta.',metric:'architecture',impact:18,fields:[{key:'entry',label:'De onde o guia deve receber contexto',options:[['category','Da categoria de tênis de corrida'],['home','De um banner genérico na home'],['product','De cópias do guia nos produtos']]},{key:'connection',label:'Para onde o guia deve conduzir',options:[['product','Para produtos relacionados, por links contextuais'],['none','Para nenhum próximo conteúdo'],['duplicate','Para o mesmo texto duplicado']]}],ready:s=>s.entry&&s.connection,validate:s=>s.entry==='category'&&s.connection==='product',feedback:'Links internos contextuais dão sentido à jornada e ajudam o buscador a compreender a relação entre as páginas.'},
  {type:'builder',builder:'scenario',title:'A consulta revela uma intenção',copy:'Uma pessoa pesquisa “como saber meu tipo de pisada”. Monte a primeira resposta da Veloce para o momento em que ela está.',metric:'relevance',impact:20,fields:[{key:'intent',label:'Intenção identificada',options:[['info','Informacional — quer entender'],['transaction','Transacional — quer comprar agora'],['brand','Navegacional — quer a marca']]},{key:'page',label:'Primeira página entregue',options:[['guide','Guia explicativo com critérios e linguagem simples'],['checkout','Checkout do Velocity Pro'],['institutional','Página institucional da marca']]}],ready:s=>s.intent&&s.page,validate:s=>s.intent==='info'&&s.page==='guide',feedback:'A intenção é informacional: um conteúdo didático, claro e confiável responde à dúvida antes de sugerir qualquer próximo passo.'},
  {type:'builder',builder:'scenario',title:'Escolha a prioridade da próxima semana',copy:'A categoria tem visitas, mas pouca permanência. A página só traz produtos e nenhum critério de escolha. Defina o problema e a melhoria prioritária.',metric:'relevance',impact:18,fields:[{key:'diagnosis',label:'Diagnóstico principal',options:[['value','A página não ajuda a pessoa a decidir'],['traffic','Faltam acessos pagos'],['keyword','A palavra-chave aparece poucas vezes']]},{key:'priority',label:'Melhoria prioritária',options:[['help','Adicionar orientação, filtros compreensíveis e links para o guia'],['repeat','Repetir “tênis de corrida” no title'],['buy','Comprar mais tráfego para a mesma página']]}],ready:s=>s.diagnosis&&s.priority,validate:s=>s.diagnosis==='value'&&s.priority==='help',feedback:'A prioridade é melhorar o valor da página: informação útil, caminhos claros e conexões com o conteúdo que apoia a decisão.'}
];
const metricBase={crawl:42,index:35,architecture:48,relevance:30};
const metricElements={crawl:['crawl-score','crawl-bar'],index:['index-score','index-bar'],architecture:['architecture-score','architecture-bar'],relevance:['relevance-score','relevance-bar']};
function shuffle(items){const result=[...items];for(let index=result.length-1;index>0;index--){const swapIndex=Math.floor(Math.random()*(index+1));[result[index],result[swapIndex]]=[result[swapIndex],result[index]];}if(result.length>1&&result.every((item,index)=>item===items[index]))result.push(result.shift());return result;}
questions.forEach(q=>{if(q.options)q.options=q.options.map((option,index)=>({option,correct:index===q.correct}));});
function shuffleChoiceOptions(){questions.forEach(q=>{if(q.options)q.options=shuffle(q.options);});}
document.querySelector('.step-dots').innerHTML=questions.map((_,index)=>`<i class="${index===0?'active':''}"></i>`).join('');
let current=0,selected=null,reviewed=false,correctAnswers=0,metricValues={...metricBase},builderState={};
const area=document.querySelector('#question-area'),next=document.querySelector('#next-question');
const robotsItems=[['home','Home','/'],['produtos','Produtos','/produto/'],['categorias','Categorias','/tenis-corrida/'],['guias','Guias','/guia/'],['busca','Busca interna','/busca/'],['filtros','Filtros','/filtros/'],['checkout','Checkout','/checkout/'],['conta','Minha conta','/conta/'],['campanhas','Campanhas antigas','/campanha/'],['admin','Administração','/admin/']];
const sitemapItems=[['categoria','Categoria de corrida','/tenis-corrida/'],['produto','Produto Velocity Pro','/produto/velocity-pro/'],['guia','Guia para iniciantes','/guia/primeiro-tenis/'],['busca','Resultado de busca','/busca?q=tenis'],['filtro','Filtro por cor','/tenis-corrida/?cor=azul'],['campanha','Produto com UTM','/produto/velocity-pro?utm=mail'],['checkout','Checkout','/checkout/'],['esgotado','Produto esgotado','/produto/velocity-2019/'],['erro','Página 404','/erro-404/'],['login','Área de login','/minha-conta/']];
const routeOptions={category:[['','Escolha a categoria'],['corrida','/tenis-corrida/'],['parametro','/tenis?tipo=corrida'],['generico','/categoria?id=7']],guide:[['','Escolha o guia'],['guia','/tenis-corrida/guia-iniciantes/'],['solto','/blog/post-92'],['parametro','/tenis?pagina=guia']],product:[['','Escolha o produto'],['produto','/tenis-corrida/velocity-pro/'],['solto','/produto?id=152'],['promo','/oferta-velocity-agora']]};
const briefOptions={format:['Guia comparativo','Página de produto','Post de tendências'],elements:['Critérios de escolha','Modelos e faixas de preço','História da marca','Botão de checkout'],next:['Explorar categorias','Ir ao checkout','Assinar newsletter']};
const canonicalUrls=['https://veloce.com.br/tenis-velocity-pro/','https://veloce.com.br/tenis-velocity-pro?utm_source=instagram','https://veloce.com.br/tenis-velocity-pro?cor=azul','https://veloce.com.br/busca?q=velocity','https://veloce.com.br/tenis-velocity-pro?utm_campaign=black-friday','https://veloce.com.br/tenis-velocity-pro?size=40'];
const onpageOptions={url:[['boa','/tenis-corrida/iniciantes/'],['ruim','/p/123'],['ruim','/tenis?publico=iniciantes'],['ruim','/categoria/12345']],title:[['bom','Tênis de corrida para iniciantes | Veloce'],['ruim','Tênis tênis tênis tênis tênis'],['ruim','Produtos | Veloce'],['ruim','O melhor tênis do mundo']],h1:[['bom','Como escolher seu primeiro tênis de corrida'],['ruim','Tênis de corrida para iniciantes'],['ruim','Bem-vindo à Veloce'],['ruim','Comprar agora']],content:[['bom','Critérios, modelos e orientação para decidir'],['ruim','Só um banner de compra'],['ruim','Texto genérico sem comparação'],['ruim','Lista de palavras-chave sem contexto']],image:[['bom','Imagem com alt contextual'],['ruim','Imagem sem alt'],['ruim','Imagem decorativa sem relação com o tema'],['ruim','Imagem com alt “tênis tênis tênis”']]};
function reshuffle(items){items.splice(0,items.length,...shuffle(items));}
function shuffleBuilderChoices(){reshuffle(robotsItems);reshuffle(sitemapItems);Object.values(routeOptions).forEach(options=>options.splice(1,options.length-1,...shuffle(options.slice(1))));Object.values(briefOptions).forEach(reshuffle);reshuffle(canonicalUrls);Object.values(onpageOptions).forEach(reshuffle);questions.filter(q=>q.builder==='scenario').forEach(q=>q.fields.forEach(field=>reshuffle(field.options)));}
function builderMarkup(q){
  if(q.builder==='robots'){const lines=robotsItems.filter(([id])=>builderState[id]).map(([id,,path])=>`${builderState[id]}: ${path}`).join('\n')||'# suas decisões aparecerão aqui';return `<div class="builder-grid robots-builder"><div class="builder-panel"><p class="builder-kicker">ÁREAS DO SITE · 10 DECISÕES</p>${robotsItems.map(([id,label,path])=>`<div class="rule-row"><span><b>${label}</b><small>${path}</small></span><div class="rule-actions"><button type="button" class="rule-choice ${builderState[id]==='Allow'?'is-allow':''}" data-rule="${id}" data-value="Allow">Allow</button><button type="button" class="rule-choice ${builderState[id]==='Disallow'?'is-block':''}" data-rule="${id}" data-value="Disallow">Disallow</button></div></div>`).join('')}</div><aside class="live-preview code-preview"><span>robots.txt</span><pre>User-agent: *\n${lines}</pre></aside></div>`;}
  if(q.builder==='sitemap'){const selectedItems=sitemapItems.filter(([id])=>builderState[id]);return `<div class="builder-grid"><div class="selection-list">${sitemapItems.map(([id,label,path])=>`<button type="button" class="pick-card ${builderState[id]?'picked':''}" data-sitemap="${id}"><i>${builderState[id]?'✓':'+'}</i><span>${label}<small>${path}</small></span></button>`).join('')}</div><aside class="live-preview code-preview"><span>sitemap.xml · ${selectedItems.length}/3</span><pre>&lt;urlset&gt;\n${selectedItems.map(([, ,path])=>`  &lt;url&gt;${path}&lt;/url&gt;`).join('\n')||'  <!-- selecione 3 URLs -->'}\n&lt;/urlset&gt;</pre></aside></div>`;}
  if(q.builder==='architecture'){const select=(key,label)=>`<label class="field-select">${label}<select data-route="${key}">${routeOptions[key].map(([value,text])=>`<option value="${value}" ${builderState[key]===value?'selected':''}>${text}</option>`).join('')}</select></label>`;const c=routeOptions.category.find(x=>x[0]===builderState.category)?.[1]||'/…';const g=routeOptions.guide.find(x=>x[0]===builderState.guide)?.[1]||'/…';const p=routeOptions.product.find(x=>x[0]===builderState.product)?.[1]||'/…';return `<div class="builder-grid"><div class="route-controls">${select('category','Página pilar')} ${select('guide','Conteúdo de apoio')} ${select('product','Produto')}</div><aside class="live-preview route-map"><span>MAPA DE NAVEGAÇÃO</span><b>HOME</b><i>└─ ${c}</i><i> &nbsp;&nbsp;├─ ${g}</i><i> &nbsp;&nbsp;└─ ${p}</i></aside></div>`;}
  if(q.builder==='brief'){const chip=(value,kind)=>`<button type="button" class="brief-choice ${kind==='element'&&builderState.elements?.includes(value)||builderState[kind]===value?'picked':''}" data-brief-kind="${kind}" data-brief-value="${value}">${value}</button>`;return `<div class="builder-grid"><div class="brief-controls"><p>FORMATO</p><div class="choice-row">${briefOptions.format.map(v=>chip(v,'format')).join('')}</div><p>O QUE ENTRA</p><div class="choice-row">${briefOptions.elements.map(v=>chip(v,'element')).join('')}</div><p>PRÓXIMO PASSO</p><div class="choice-row">${briefOptions.next.map(v=>chip(v,'next')).join('')}</div></div><aside class="live-preview brief-preview"><span>BRIEFING EM CONSTRUÇÃO</span><b>${builderState.format||'Escolha o formato'}</b><p>${builderState.elements?.join(' · ')||'Defina os elementos úteis'}</p><em>${builderState.next||'Escolha o próximo passo'}</em></aside></div>`;}
  if(q.builder==='canonical'){return `<div class="builder-grid"><div class="url-stack">${canonicalUrls.map(url=>`<button type="button" class="url-choice ${builderState.url===url?'picked':''}" data-canonical="${url}"><i>${builderState.url===url?'✓':'○'}</i>${url}</button>`).join('')}</div><aside class="live-preview code-preview"><span>TAG GERADA</span><pre>${builderState.url?`&lt;link rel="canonical"\n  href="${builderState.url}"&gt;`:'&lt;link rel="canonical" href="…"&gt;'}</pre></aside></div>`;}
  if(q.builder==='scenario'){const fields=q.fields.map(field=>`<label class="field-select">${field.label}<select data-scenario="${field.key}"><option value="">Escolha uma opção</option>${field.options.map(([value,text])=>`<option value="${value}" ${builderState[field.key]===value?'selected':''}>${text}</option>`).join('')}</select></label>`).join('');const summary=q.fields.map(field=>{const option=field.options.find(([value])=>value===builderState[field.key]);return `<i>${field.label}: ${option?.[1]||'…'}</i>`;}).join('');return `<div class="builder-grid"><div class="route-controls">${fields}</div><aside class="live-preview route-map"><span>DECISÃO EM CONSTRUÇÃO</span><b>${q.title}</b>${summary}</aside></div>`;}
  const fields=Object.entries(onpageOptions).map(([key,choices])=>`<label class="field-select">${key.toUpperCase()}<select data-onpage="${key}"><option value="">Escolha uma opção</option>${choices.map(([value,text])=>`<option value="${value}" ${builderState[key]===value?'selected':''}>${text}</option>`).join('')}</select></label>`).join('');return `<div class="builder-grid"><div class="route-controls onpage-controls">${fields}</div><aside class="live-preview serp-preview"><span>PRÉVIA NA BUSCA</span><b>${builderState.title==='bom'?'Tênis de corrida para iniciantes | Veloce':'Título da página'}</b><i>veloce.com.br${builderState.url==='boa'?'/tenis-corrida/iniciantes/':'/…'}</i><p>${builderState.content==='bom'?'Critérios e modelos para escolher o seu primeiro tênis de corrida.':'Descrição da página e seus conteúdos.'}</p><em>${builderState.h1==='bom'?'H1: Como escolher seu primeiro tênis de corrida':'H1: …'}</em></aside></div>`;
}
function paintBuilder(q){area.innerHTML=`<div class="question-intro"><span class="question-kicker">CONSTRUA A RESPOSTA</span><h3 class="question-title">${q.title}</h3><p class="question-copy">${q.copy}</p></div>${builderMarkup(q)}`;selected=builderState;next.disabled=!q.ready(builderState);area.querySelectorAll('.rule-choice').forEach(button=>button.addEventListener('click',()=>{builderState[button.dataset.rule]=button.dataset.value;paintBuilder(q);}));area.querySelectorAll('.pick-card').forEach(button=>button.addEventListener('click',()=>{builderState[button.dataset.sitemap]=!builderState[button.dataset.sitemap];paintBuilder(q);}));area.querySelectorAll('[data-route]').forEach(control=>control.addEventListener('change',()=>{builderState[control.dataset.route]=control.value;paintBuilder(q);}));area.querySelectorAll('.brief-choice').forEach(button=>button.addEventListener('click',()=>{const kind=button.dataset.briefKind,value=button.dataset.briefValue;if(kind==='element'){const items=builderState.elements||[];builderState.elements=items.includes(value)?items.filter(item=>item!==value):[...items,value];}else builderState[kind]=value;paintBuilder(q);}));area.querySelectorAll('[data-canonical]').forEach(button=>button.addEventListener('click',()=>{builderState.url=button.dataset.canonical;paintBuilder(q);}));area.querySelectorAll('[data-onpage]').forEach(control=>control.addEventListener('change',()=>{builderState[control.dataset.onpage]=control.value;paintBuilder(q);}));area.querySelectorAll('[data-scenario]').forEach(control=>control.addEventListener('change',()=>{builderState[control.dataset.scenario]=control.value;paintBuilder(q);}));}
function renderQuestion(){const q=questions[current];document.querySelector('#step-label').textContent=`MISSÃO ${current+1} DE ${questions.length}`;document.querySelectorAll('.step-dots i').forEach((dot,i)=>dot.classList.toggle('active',i===current));area.classList.remove('is-reviewed');selected=null;reviewed=false;next.disabled=true;next.style.visibility='';next.innerHTML=q.type==='builder'?'Confirmar escolhas <span>→</span>':'Confirmar seleção <span>→</span>';if(q.type==='builder'){builderState={};paintBuilder(q);return;}const interaction=`<div class="options">${q.options.map((item,i)=>`<button class="option" data-index="${i}"><span class="option-number">${String(i+1).padStart(2,'0')}</span><span><b>${item.option[0]}</b></span><span class="option-arrow">→</span></button>`).join('')}</div>`;area.innerHTML=`<div class="question-intro"><span class="question-kicker">CENÁRIO DE DECISÃO</span><h3 class="question-title">${q.title}</h3><p class="question-copy">${q.copy}</p></div>${interaction}`;area.querySelectorAll('.option').forEach(option=>option.addEventListener('click',()=>{area.querySelectorAll('.option').forEach(item=>item.classList.remove('selected'));option.classList.add('selected');selected=+option.dataset.index;next.disabled=false;}));}
function updateMetric(metric,good,impact){const [scoreId,barId]=metricElements[metric];metricValues[metric]=Math.min(100,metricValues[metric]+(good?impact:Math.ceil(impact*.15)));document.querySelector('#'+scoreId).textContent=metricValues[metric]+'%';document.querySelector('#'+barId).style.width=metricValues[metric]+'%';}
next.addEventListener('click',()=>{const q=questions[current];if(reviewed){if(current===questions.length-1)renderResult();else{current++;renderQuestion();}return;}if(selected===null)return;const good=q.type==='builder'?q.validate(builderState):q.options[selected].correct;if(good)correctAnswers++;document.querySelector('#score').textContent=Math.round(correctAnswers/questions.length*100)+' pts';updateMetric(q.metric,good,q.impact);reviewed=true;area.classList.add('is-reviewed');area.querySelectorAll('button, select').forEach(control=>control.disabled=true);if(q.type==='choice')area.querySelectorAll('.option').forEach((option,index)=>option.classList.add(q.options[index].correct?'is-correct':index===selected?'is-wrong':''));const message=good?`Boa decisão. ${q.feedback}`:`${q.feedback}`;area.insertAdjacentHTML('beforeend',`<div class="answer-feedback ${good?'is-good':'is-revise'}"><span class="feedback-mark">${good?'✓':'↗'}</span><div><strong>${good?'Boa decisão':'Vamos ajustar a rota'}</strong><p>${message}</p></div></div>`);next.disabled=false;next.innerHTML=current===questions.length-1?'Ver resultado <span>→</span>':'Avançar <span>→</span>';});
function renderResult(){const student=nameInput.value.trim()||'Visitante',points=Math.round(correctAnswers/questions.length*100);document.querySelector('#step-label').textContent='DIAGNÓSTICO CONCLUÍDO';area.innerHTML=`<div class="result"><span class="result-score">RESULTADO DE ${student.toUpperCase()}: ${points}/100 · ${correctAnswers} DE ${questions.length} MISSÕES</span><h3>${student}, você percorreu a trilha inteira.</h3><p>Sua nota geral considera robots.txt, sitemap.xml, estrutura de URLs, conteúdo por intenção de busca, URLs canônicas e SEO on-page. O painel lateral mostra a saúde projetada da Veloce após suas decisões.</p><p><strong>Próximo passo:</strong> explore novamente os módulos da trilha e teste novas decisões.</p></div>`;next.style.display='none';document.querySelector('#restart').style.display='inline-block';}
document.querySelector('#restart').addEventListener('click',()=>{current=0;selected=null;correctAnswers=0;metricValues={...metricBase};document.querySelector('#score').textContent='0 pts';Object.entries(metricBase).forEach(([metric,value])=>{const [scoreId,barId]=metricElements[metric];document.querySelector('#'+scoreId).textContent=value+'%';document.querySelector('#'+barId).style.width=value+'%';});next.style.display='inline-flex';shuffleChoiceOptions();shuffleBuilderChoices();renderQuestion();});
shuffleChoiceOptions();shuffleBuilderChoices();renderQuestion();
